hostname = "iotedge"
homedir = "/var/lib/aziot/identityd"

[connect]
api_uri = "unix:///var/run/aziot/identityd.sock"

[listen]
api_uri = "unix:///var/run/aziot/identityd.sock"

# Identity service configuration used to associate provisioned device and module identities to host-level processes.
# This configuration will also be used to generate new module identities, if not created in Azure IoT Hub already.
# [[principal]]
# name = "hostdaemon1"
# uid = 1001

# [[principal]]
# name = "hostprocess1"
# idtype = "device"
# uid = 1002

# [[principal]]
# name = "hostprocess2"
# idtype = "module"
# uid = 1003
