hostname = "iotedge"
homedir = "/var/lib/aziot/common"

# Manual provisioning configuration using a connection string
[provisioning]
source = "manual"
device_connection_string = "<ADD DEVICE CONNECTION STRING HERE>"
dynamic_reprovisioning = false

[cert_issuance]
device-id = "dps"
module-id = "dps"
module-server = "dps"

#[provisioning]
#"source" = "dps"
#"scope_id" = "<ADD DPS SCOPE ID HERE>"
#
#[provisioning.attestation]
#"method" = "x509"
#"identity_cert" = "device-id"
#"identity_pk" = "device-id"


# EST provisioning case
# [provisioning]
# "source" = "dps"
# "scope_id" = "<ADD dps SCOPE ID HERE>"

# [provisioning.attestation]
# "method" = "x509"
# "identity_cert" = "est"
# "identity_pk" = "est"

# [cert_issuance]
# device-ca = "est" # Only needed if one of the others has the value "device-ca"
# device-id = "est" # or "device-ca" for minting locally
# module-id = "est" # or "device-ca" for minting locally
# module-server = "est" # or "device-ca" for minting locally

# [est.url]
# # Default EST endpoint URL
# default = "https://estendpoint.com/.well-known/est/simpleenroll"

# # EST endpoint URL specifically for the device-id cert
# "device-id" = "https://estendpoint.com/.well-known/est/device-id/simpleenroll"

# # EST endpoint URL specifically for the device-ca cert
# "device-ca" = "https://estendpoint.com/.well-known/est/device-ca/simpleenroll"
